# Sanitizers
option(ENABLE_ADDRESS_SANITIZER "Enable AddressSanitizer (only in debug under linux)" OFF)
option(ENABLE_UNDEFINED_BEHAVIOR_SANITIZER "Enable UndefinedBehavior (only in debug under linux)" OFF)

if (NOT OPP_COMPILER_MSVC)
    if (CMAKE_BUILD_TYPE MATCHES "Debug")
        set(SANITIZER_COUNT 0)
        if (ENABLE_ADDRESS_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=address -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_THREAD_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=thread -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_MEMORY_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=memory -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_UNDEFINED_BEHAVIOR_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=undefined -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_DATA_FLOW_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=dataflow -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_CONTROL_FLOW_INTEGRITY_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=cfi -flto -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()
        if (ENABLE_SAFE_STACK_SANITIZER)
            MATH(EXPR SANITIZER_COUNT "${SANITIZER_COUNT}+1")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=safe-stack -O0 -g3 -fno-omit-frame-pointer -fno-optimize-sibling-calls")
        endif ()

        if (SANITIZER_COUNT GREATER 1)
            message(FATAL_ERROR "You can only use sanitizers one by one.")
        endif ()
    endif ()
endif ()